### ISSUE TITLE
OpenCL+CUDA mode causes not-connected

### ISSUE THREAD

**Issue by EoD** [ethereum-mining/ethminer#1028]
When I am using either ``-U`` or ``-G`` ethminer works fine. As soon as I use ``-X`` it causes the following

```
 .\ethminer.15dev4.exe -X -RH -P stratum+ssl://1234567890abcdef@us1.ethermine.org:5555
  m  02:24:57|main    |  ethminer version 0.15.0.dev4
  m  02:24:57|main    |  Build: windows / release +git. 30df0e6
  i  02:24:57|main    |  Found suitable OpenCL device [...]
 cu  02:24:57|main    |  Using grid size 8192 , block size 128
  m  02:24:57|main    |  not-connected
  i  02:24:57|stratum |  Connected to us1.ethermine.org:5555
  i  02:24:57|stratum |  Spinning up miners...
  i  02:24:57|cuda-0  |  No work. Pause for 3 s.
 cl  02:24:57|cl-1    |  No work. Pause for 3 s.
  i  02:25:00|cuda-0  |  No work. Pause for 3 s.
 cl  02:25:00|cl-1    |  No work. Pause for 3 s.
  m  02:25:02|main    |  not-connected
  i  02:25:03|cuda-0  |  No work. Pause for 3 s.
 cl  02:25:03|cl-1    |  No work. Pause for 3 s.
  i  02:25:06|cuda-0  |  No work. Pause for 3 s.
 cl  02:25:06|cl-1    |  No work. Pause for 3 s.
  m  02:25:07|main    |  not-connected
```

**Comment by AndreaLanfranchi** [comment]
Please.
Could you try using simple stratum+tcp instead of stratum+ssl ?

`.\ethminer.15dev4.exe -X -RH -P stratum+tcp://1234567890abcdef@us1.ethermine.org:4444`

**Comment by EoD** [comment]
@AndreaLanfranchi It makes no difference of course. I mentioned that the same commands works fine with both ``-G`` and ``-U``, so I doubt it is related to ssl.

**Comment by deathmarine** [comment]
I believe the title to this issue is more about after having an internet service interruption then anything.

```
##Mining just fine for ~6 hours...
  X  05:19:44|stratum |  Read response failed: The semaphore timeout period has expired
  i  05:19:44|stratum |  Disconnected from us1.ethermine.org
  i  05:19:44|stratum |  Shutting down miners...
  i  05:19:44|stratum |  Retrying in 3 ...
  m  05:19:45|main    |  not-connected
  i  05:19:45|stratum |  Retrying in 2 ...
  i  05:19:46|stratum |  Retrying in 1 ...
  m  05:19:50|main    |  not-connected
  m  05:19:55|main    |  not-connected
  X  05:19:59|stratum |  Could not resolve host us1.ethermine.org:4444, No such host is known
  m  05:20:00|main    |  not-connected
  m  05:20:05|main    |  not-connected
  m  05:20:10|main    |  not-connected
  m  05:20:15|main    |  not-connected
  m  05:20:20|main    |  not-connected
  m  05:20:25|main    |  not-connected
  m  05:20:30|main    |  not-connected
  m  05:20:35|main    |  not-connected
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  m  07:46:13|main    |  not-connected
  m  07:46:18|main    |  not-connected
  m  07:46:23|main    |  not-connected
  m  07:46:28|main    |  not-connected
  m  07:46:33|main    |  not-connected
  m  07:46:38|main    |  not-connected
  m  07:46:43|main    |  not-connected
```

Using -G and -P argument stratum+tcp (<-- this needs some documentation).
https://github.com/ethereum-mining/ethminer/blob/f27c5b58431ec63c8c9a2bec97f7c282f5b45e43/libpoolprotocols/PoolURI.cpp#L18-L30

**Comment by EoD** [comment]
@deathmarine No, it is not. What you are describing is #1019 or even #988. It is **not** about ``-X`` at all.

**Comment by chfast** [comment]
@deathmarine, you issues is fixed in #1027

**Comment by peruginia** [comment]
hy, with ethminer 0.15.0.dev10 windows i have the same problem.

**Comment by AnjinMeili** [comment]
Please see #959.  This issue is not fixed.  It seems related to the way mixed rigs are handled.

**Comment by EoD** [comment]
Duplicate of #959
