### ISSUE TITLE
Doesn't compile under Visual Studio 2017

### ISSUE THREAD

**Issue by marcelinojorgeromero** [ethereum-mining/ethminer#37]
I am trying to compile the project with CUDA support but i can't it throws me the following error:
I think it's because in [Visual Studio 2017 they changed the bin directory](https://blogs.msdn.microsoft.com/vcblog/2016/10/07/compiler-tools-layout-in-visual-studio-15/)

> Project "C:\ethminer\build\ALL_BUILD.vcxproj" (1) is building "C:\ethminer\build\libethash-
> cuda\ethash-cuda.vcxproj" (6) on node 1 (default targets).
> PrepareForBuild:
>   Creating directory "ethash-cuda.dir\Debug\".
>   Creating directory "C:\ethminer\build\libethash-cuda\Debug\".
>   Creating directory "ethash-cuda.dir\Debug\ethash-cuda.tlog\".
> InitializeBuildStatus:
>   Creating "ethash-cuda.dir\Debug\ethash-cuda.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
> ComputeCustomBuildOutput:
>   Creating directory "C:\ethminer\build\libethash-cuda\CMakeFiles\ethash-cuda.dir\Debug\".
> CustomBuild:
>   Building NVCC (Device) object libethash-cuda/CMakeFiles/ethash-cuda.dir/Debug/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.obj
> CUSTOMBUILD : nvcc warning : The 'compute_20', 'sm_20', and 'sm_21' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targe
> ts to suppress warning). [C:\ethminer\build\libethash-cuda\ethash-cuda.vcxproj]
>   CMake Error at ethash-cuda_generated_ethash_cuda_miner_kernel.cu.obj.Debug.cmake:222 (message):
>     Error generating
>     C:/ethminer/build/libethash-cuda/CMakeFiles/ethash-cuda.dir//Debug/ethash-cuda_generated_ethash_cuda_miner_kernel.cu.obj
> 
> 
>   Failed to run C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/bin (The system cannot find the file specified.
> 
>   ).
> C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1
> . [C:\ethminer\build\libethash-cuda\ethash-cuda.vcxproj]
> Done Building Project "C:\ethminer\build\libethash-cuda\ethash-cuda.vcxproj" (default targets) -- FAILED.

**Comment by heinreich** [comment]
I'm having the same problem and am too savy with C++. Is there a way to fix this?

**Comment by freiro** [comment]
Similar error here, Windows 10, VS 2017, error during the configuring fase on cmake-gui:


```
CustomBuild:

  Building Custom Rule C:/.hunter/_Base/435b09a/61c532d/863fb14/Build/Boost/CMakeLists.txt

  CMake does not need to re-run because C:/.hunter/_Base/435b09a/61c532d/863fb14/Build/Boost/Build/CMakeFiles/generate.stamp is up-to-date.

  Creating directories for 'Boost'

  Performing download step (download, verify and extract) for 'Boost'

  -- Boost download command succeeded.  See also C:/.hunter/_Base/435b09a/61c532d/863fb14/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-download-*.log

  No update step for 'Boost'

  No patch step for 'Boost'

  Performing configure step for 'Boost'

  -- Boost configure command succeeded.  See also C:/.hunter/_Base/435b09a/61c532d/863fb14/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-configure-*.log

  No build step for 'Boost'

  Performing install step for 'Boost'

  CMake Error at C:/.hunter/_Base/435b09a/61c532d/863fb14/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug.cmake:16 (message):

    Command failed: 1
  

     'C:/Program Files/CMake/bin/cmake.exe' '-Dmake=' '-Dconfig=Debug' '-P' 'C:/.hunter/_Base/435b09a/61c532d/863fb14/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug-impl.cmake'
  

    See also
  
      C:/.hunter/_Base/435b09a/61c532d/863fb14/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-*.log
  .......................................................



[hunter ** FATAL ERROR **] Build step failed (dir: C:/.hunter/_Base/435b09a/61c532d/863fb14/Build/Boost
[hunter ** FATAL ERROR **] [Directory:C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/projects/Boost]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_download.cmake:550 (hunter_fatal_error)
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/projects/Boost/hunter.cmake:259 (hunter_download)
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_add_package.cmake:87 (include)
  CMakeLists.txt:86 (hunter_add_package)


Configuring incomplete, errors occurred!
```

**Comment by keraj37** [comment]
@freiro check you file: C:/.hunter/_Base/435b09a/61c532d/863fb14/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-err.log, and most likely you don't have installed b2.exe or path to it is not set.

Install boost first.

I am having issue with building for CUDA too, but I am working on it now, and I think I have an idea. Will post solution if any.

**Comment by keraj37** [comment]
So I just managed to build for CUDA, having more less exactly same error messages.

For me the solution was to

1. Use VS 15 **Win64** instead of Win32 generator for cmake.
2. And giving to cmake manually the path to **cl.exe** when cmake ask you for host compiler for nvcc. For me this path is: _C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\cl.exe_.

@marcelinojorgeromero I am almost sure that you main issue is giving wrong path to cl.exe. Most likely you left default **${VC somthing}/bin**, and that is why you have this message:

> Failed to run C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/bin (The system cannot find the file specified.

**Comment by rkjames** [comment]
This is fixed with this commit:
https://github.com/ethereum-mining/ethminer/pull/160

(Visual Studio 2017 moved vcvarsall.bat, breaking older hunter)

**Comment by janbernloehr** [comment]
There seem to be issues with CUDA 9.1 and Visual C++ 2017 Compiler starting with version 15.3 and newer.

To build ethminer nontheless, [install the VS 2015 compiler with the VS2017 installer](https://stackoverflow.com/questions/43745099/using-cuda-with-visual-studio-2017).

Then build with
```
mkdir build; cd build
cmake .. -G "Visual Studio 15 2017 Win64" -Tv140 -DETHASHCL=OFF -DETHASHCUDA=ON
cmake --build . --config Release
```

You may run into another issue during the boost build which requires you to alter the file `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat` by changing line `10` into
````
rem if not exist "%~dp0..\common7\IDE\wdexpress.exe" goto setup_buildsku
````
(note the `rem` prefix)

**Comment by oculushut** [comment]
@janbernloehr I rem'd out the line you mentioned and still getting an error on the Boost part.  Did you try anything else to get it working?  Here's what I have so far:

```
  Performing install step for 'Boost'
  CMake Error at C:/.hunter/_Base/435b09a/61c532d/0ba076c/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug.cmake:16 (message):
    Command failed: 1

     'C:/Program Files/CMake/bin/cmake.exe' '-Dmake=' '-Dconfig=Debug' '-P' 'C:/.hunter/_Base/435b09a/61c532d/0ba076c/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-Debug-impl

    See also

      C:/.hunter/_Base/435b09a/61c532d/0ba076c/Build/Boost/Build/Boost-prefix/src/Boost-stamp/Boost-install-*.log


C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\.hunter\_Base\435b09a\61c532d\0ba076c\Build\Boost
Done Building Project "C:\.hunter\_Base\435b09a\61c532d\0ba076c\Build\Boost\Build\Boost.vcxproj" (default targets) -- FAILED.
Done Building Project "C:\.hunter\_Base\435b09a\61c532d\0ba076c\Build\Boost\Build\ALL_BUILD.vcxproj" (default targets) -- FAILED.

Build FAILED.

"C:\.hunter\_Base\435b09a\61c532d\0ba076c\Build\Boost\Build\ALL_BUILD.vcxproj" (default target) (1) ->
"C:\.hunter\_Base\435b09a\61c532d\0ba076c\Build\Boost\Build\Boost.vcxproj" (default target) (3) ->
(CustomBuild target) ->
  C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(171,5): error MSB6006: "cmd.exe" exited with code 1. [C:\.hunter\_Base\435b09a\61c532d\0ba076c\Build\Boo

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:07:50.99

[hunter ** FATAL ERROR **] Build step failed (dir: C:/.hunter/_Base/435b09a/61c532d/0ba076c/Build/Boost
[hunter ** FATAL ERROR **] [Directory:C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/projects/Boost]

------------------------------ WIKI -------------------------------
    https://github.com/ruslo/hunter/wiki/error.external.build.failed
-------------------------------------------------------------------

CMake Error at C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_wiki.cmake:12 (message):
Call Stack (most recent call first):
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_fatal_error.cmake:20 (hunter_wiki)
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_download.cmake:550 (hunter_fatal_error)
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/projects/Boost/hunter.cmake:259 (hunter_download)
  C:/.hunter/_Base/Download/Hunter/0.18.57/435b09a/Unpacked/cmake/modules/hunter_add_package.cmake:87 (include)
  CMakeLists.txt:86 (hunter_add_package)


-- Configuring incomplete, errors occurred!
See also "C:/dev/cpp-ethereum/build/CMakeFiles/CMakeOutput.log".
```

**Comment by Davesmacer** [comment]
At the begining I had some VS related issues, very similar of what you're getting, but commands 

cmake .. -G "Visual Studio 15 2017 Win64" -Tv140 -DETHASHCL=OFF -DETHASHCUDA=ON
cmake --build . --config Release

Given by @janbernloehr solved them after a Windows reboot. Remember you have to install VS2015 compilers with VS2017 installer. Reboot after installation.

I'm able to compile with Windows 10 and Windows 7 using CUDA 9.0 and VS2017

**Comment by DeadManWalkingTO** [comment]
I think the solution has been found.

**Comment by Davesmacer** [comment]
Also, I had issues compiling with VS 2017. It is a known issue while using VS 2015 compiler:
https://developercommunity.visualstudio.com/content/problem/22031/unusable-vc-build-tools-2015-installed-with-vs2017.html
that should solve it

**Comment by DeadManWalkingTO** [comment]
I have VS 2017 and MS Build Tools 2015. No issue. Compile was successful.
