### ISSUE TITLE
ethminer on nicehash only getting rejects

### ISSUE THREAD

**Issue by AyaNekoGirl16** [ethereum-mining/ethminer#563]
Hi, i just tried mining on nicehash using the newest 0.13 RC6 i only get rejects, never accepts.
I reverted back to 0.12 and it works there. I dunno on which version it started breaking. i haven't tried the other RC versions.

**Comment by tobutridaz** [comment]
Same issue for me on the pre-releases mining against https://coinfoundry.org/ 
100% rejects

**Comment by othocaes** [comment]
Confirmed happening on RC7 for nicehash.

**Comment by jean-m-cyr** [comment]
@AyaNekoGirl16 @tobutridaz @othocaes This is fixed by pull request #588. Thanks for testing. I don't usually go to those pools. Continuous integration appears to be busted right now so I don't know how soon it will get merged.

**Comment by jagerman** [comment]
#588 doesn't appear to have fixed this.  I rebuilt current `master`, verified that the changes from #588 are applied, and still get:

```
  ℹ  22:37:12|cl-0      Solution found; Submitted to daggerhashimoto.usa.nicehash.com
  ℹ  22:37:12|stratum   Invalid job id size.
  ✘  22:37:12|stratum   Rejected.
```

**Comment by jagerman** [comment]
Bisected this to 41a91af639bfc6dd00ea1b2e885b260ae372445a causing the problem.

**Comment by jagerman** [comment]
Here are three sample submitted JSON values, by the last working (41a91af), first broken (4e48cde), and current master (which has #588 applied):
```
{"id": 4, "method": "mining.submit", "params": ["3Kd...","000000047f6d0e07","00006b8ee5"]}
{"id": 4, "method": "mining.submit", "params": ["3Kd...","0000000000000000000000000000000000000000000000000000000000000000","000d646fca"]}
{"id": 4, "method": "mining.submit", "params": ["3Kd...","00000000","0004b4a58a"]}
```
All were preceded by `Received new job #00000004  seed: #...`; the job number is snipped in that output to the first 8 chars, but clearly starts with a 4 as in the first (working) one.

**Comment by jagerman** [comment]
#598 fixes this for me, tested with nicehash and the CL path (I don't have CUDA hardware installed, but I think it should work there too).
