### ISSUE TITLE
Exit miner after x failed attempts

### ISSUE THREAD

**Issue by MariusVanDerWijden** [ethereum-mining/ethminer#672]
Add an option to exit ethminer for no connection or for x amount of fails.
as specified in https://github.com/ethereum-mining/ethminer/issues/652

**Comment by gashtal** [comment]
I just came back home to see that my internet connection had died, yet my GPUs were still running full force and ethminer was trying to reconnect; I am not sure what was being mined during all this time that the connection was down, though. Either way, I believe an option to exit in case of repeated failures could be very useful.

**Comment by DeadManWalkingTO** [comment]
Just waiting #740 (Fix: Failover exit when option `-FS exit` is given)
As temporary solution after #757 (added --exit parameter to exit whenever an error occurred) you can use a watchdog.

Here is my [ETHminerWatchDogDmW](https://github.com/DeadManWalkingTO/ETHminerWatchDogDmW) Windows7/8/10 [32/64] & Linux (Any Dist/Any Ver/Any Arch) (#735).

Check and feedback please.
Thank you!

**Comment by AndreaLanfranchi** [comment]
Should all be solved now.

**Comment by Yorper** [comment]
Using 0.14.0RC10 it still does not exit on no work given. Unless I'm completely missing something, this is the command issued...

./ethminer --exit -U -P user.name:password@server.address.com:port

The miner just sits in a never ending loop of "No work. Pause for 3 s".
