### ISSUE TITLE
0.14dev2 Windows - CUDA error in func set_header

### ISSUE THREAD

**Issue by ivanovd** [ethereum-mining/ethminer#823]
_**Fatal GPU error: CUDA error in func set_header at line 147 the launch timed out and was terminated**_

The 1050Ti's are 4 GB and the 1060 is 6 GB

I have no issues with other miners

That is what I get when I start ethminer:

> C:\Users\Miner\Downloads\ethminer-dbg-0.14.0.dev2\bin>ethminer.exe --farm-recheck 200 -U -S lb.geo.pirlpool.eu:8002 -SP 1 -O 0x0a31d4170723Af650f0A467F00e012f833C5dC33.Miner
>   m  16:23:49|main    |  ethminer version 0.14.0.dev2
>   m  16:23:49|main    |  Build: Windows/msvc / Release
>  cu  16:23:50|main    |  Using grid size 8192 , block size 128
>   m  16:23:50|main    |  not-connected
>   i  16:23:50|stratum |  Connected to lb.geo.pirlpool.eu
>   i  16:23:50|stratum |  Spinning up miners...
>   i  16:23:50|cuda-0  |  No work. Pause for 3 s.
>   i  16:23:50|cuda-1  |  No work. Pause for 3 s.
>   i  16:23:50|cuda-2  |  No work. Pause for 3 s.
>   i  16:23:50|cuda-3  |  No work. Pause for 3 s.
>   i  16:23:50|cuda-4  |  No work. Pause for 3 s.
>   i  16:23:50|cuda-5  |  No work. Pause for 3 s.
>   i  16:23:50|cuda-6  |  No work. Pause for 3 s.
>   i  16:23:50|stratum |  Received new job #b9256f57 from lb.geo.pirlpool.eu
>   i  16:23:51|stratum |  Received new job #40034a9f from lb.geo.pirlpool.eu
>   i  16:23:53|cuda-0  |  Initialising miner 0
>   i  16:23:53|cuda-1  |  Initialising miner 1
>   i  16:23:53|cuda-2  |  Initialising miner 2
>   i  16:23:53|cuda-4  |  Initialising miner 4
>   i  16:23:53|cuda-3  |  Initialising miner 3
>   i  16:23:53|cuda-6  |  Initialising miner 6
>   i  16:23:53|cuda-5  |  Initialising miner 5
>  cu  16:23:54|cuda-2  |  Using device: GeForce GTX 1050 Ti  (Compute 6.1)
>  cu  16:23:54|cuda-6  |  Using device: GeForce GTX 1050 Ti  (Compute 6.1)
>  cu  16:23:54|cuda-2  |  Set Device to current
>  cu  16:23:54|cuda-4  |  Using device: GeForce GTX 1050 Ti  (Compute 6.1)
>  cu  16:23:54|cuda-1  |  Using device: GeForce GTX 1050 Ti  (Compute 6.1)
>  cu  16:23:54|cuda-6  |  Set Device to current
>  cu  16:23:54|cuda-3  |  Using device: GeForce GTX 1050 Ti  (Compute 6.1)
>  cu  16:23:54|cuda-2  |  Resetting device
>  cu  16:23:54|cuda-0  |  Using device: GeForce GTX 1060 6GB  (Compute 6.1)
>  cu  16:23:54|cuda-5  |  Using device: GeForce GTX 1050 Ti  (Compute 6.1)
>  cu  16:23:54|cuda-4  |  Set Device to current
>  cu  16:23:54|cuda-1  |  Set Device to current
>  cu  16:23:54|cuda-6  |  Resetting device
>  cu  16:23:54|cuda-3  |  Set Device to current
>  cu  16:23:54|cuda-0  |  Set Device to current
>  cu  16:23:54|cuda-5  |  Set Device to current
>  cu  16:23:54|cuda-4  |  Resetting device
>  cu  16:23:54|cuda-1  |  Resetting device
>  cu  16:23:54|cuda-3  |  Resetting device
>  cu  16:23:54|cuda-0  |  Resetting device
>  cu  16:23:54|cuda-5  |  Resetting device
>  cu  16:23:55|cuda-2  |  Allocating light with size: 20840384
>  cu  16:23:55|cuda-2  |  Generating mining buffers
>  cu  16:23:55|cuda-6  |  Allocating light with size: 20840384
>  cu  16:23:55|cuda-2  |  Generating DAG for GPU # 2  with dagSize: 1333787776  gridSize: 8192
>   m  16:23:55|main    |  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  gpu/2  0.00  gpu/3  0.00  gpu/4  0.00  gpu/5  0.00  gpu/6  0.00  [A0+0:R0+0:F0] Time: 00:00
>  cu  16:23:55|cuda-1  |  Allocating light with size: 20840384
>  cu  16:23:55|cuda-6  |  Generating mining buffers
>  cu  16:23:55|cuda-3  |  Allocating light with size: 20840384
>  cu  16:23:55|cuda-4  |  Allocating light with size: 20840384
>  cu  16:23:56|cuda-0  |  Allocating light with size: 20840384
>  cu  16:23:56|cuda-1  |  Generating mining buffers
>  cu  16:23:56|cuda-5  |  Allocating light with size: 20840384
>  cu  16:23:56|cuda-6  |  Generating DAG for GPU # 6  with dagSize: 1333787776  gridSize: 8192
>  cu  16:23:56|cuda-4  |  Generating mining buffers
>  cu  16:23:56|cuda-0  |  Generating mining buffers
>  cu  16:23:56|cuda-3  |  Generating mining buffers
>  cu  16:23:56|cuda-1  |  Generating DAG for GPU # 1  with dagSize: 1333787776  gridSize: 8192
>  cu  16:23:56|cuda-5  |  Generating mining buffers
>  cu  16:23:56|cuda-3  |  Generating DAG for GPU # 3  with dagSize: 1333787776  gridSize: 8192
>  cu  16:23:56|cuda-0  |  Generating DAG for GPU # 0  with dagSize: 1333787776  gridSize: 8192
>  cu  16:23:56|cuda-4  |  Generating DAG for GPU # 4  with dagSize: 1333787776  gridSize: 8192
>  cu  16:23:56|cuda-5  |  Generating DAG for GPU # 5  with dagSize: 1333787776  gridSize: 8192
>   X  16:23:59|cuda-6  |  Fatal GPU error: CUDA error in func set_header at line 147 the launch timed out and was terminated
>   X  16:23:59|cuda-6  |  Terminating.
>   m  16:24:02|main    |  Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  gpu/2  0.00  gpu/3  0.00  gpu/4  0.00  gpu/5  0.00  gpu/6  0.00  [A0+0:R0+0:F0] Time: 00:00

**Comment by ivanovd** [comment]
Fixed. Before running ethminer at startup I was running Claymore and then closing it. That apparently matters and running ethiner after that causes the above issues. When Claymore is not run at startup the issue is not present.

**Comment by elcopdoo** [comment]
I still get that error on GTX 1060 6GB, fresh win boot and about 1minute after starting ethminer:
"Fatal GPU error: CUDA error in func dev::eth::CUDAMiner::search at line 147 the launch timed out and was terminated."
Sometime is at line 503.
I have last version of ethminer from appveyor (ethminer version 0.14.0.dev3
  m  05:10:02|main    |  Build: windows / release +git. 5726f49)

**Comment by elcopdoo** [comment]
I also get this on GTX960M 4GB

**Comment by elcopdoo** [comment]
Any solution?

**Comment by ludvanieztha** [comment]
dont to muchb oerpower OC ethminer doesnt same as claymore trust me oc memory 700++ in this u will mostly fatal error

**Comment by quetzalcoatl** [comment]
Same issue on GF 920M (yeah, I know it's crap). No Claymore at all, just running ethminer results in "Fatal GPU error: CUDA error in func set_header at line 144 the launch timed out and was terminated". Occurs at random. Sometimes immediately at start, sometimes during DAG generation.

**Comment by AndreaLanfranchi** [comment]
Please as always.
* Which version of ethminer ?
* Which OS (Linux / Windows) ?
* How many cards ?

**Comment by nkoinhub** [comment]
Got the same error at line 144. Having ethminer-0.15.0rc1-Windows and Windows 10. 1 Card - GEFORCE GT 730 (ZOTAC). Kindly help.

**Comment by AndreaLanfranchi** [comment]
@nkoinhub please report:

- are you overclocking ?
- how much ram for you GT 730 ?

**Comment by nkoinhub** [comment]
Haven't done something additional to improve GPU performance. I am not aware about how overclocking is done. Any clues here please? The RAM is 4GB.

**Comment by AndreaLanfranchi** [comment]
Is that GTX 730 the ONLY card on your system ? I mean is it connected to your monitor ?

**Comment by nkoinhub** [comment]
Yes that GTX 730 is the only GPU, which has no monitor connected. (Connected but it's switched off.) For display, there is a built-in VGA with the motherboard, where the monitor is connected presently.

**Comment by AndreaLanfranchi** [comment]
Could you please report the output of

```
ethminer.exe -U --list-devices 
```

**Comment by nkoinhub** [comment]
Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce GT 730
        Compute version: 3.5
        cudaDeviceProp::totalGlobalMem: 4294967296
        Pci: 0000:01:00

**Comment by nkoinhub** [comment]
2432 MB

**Comment by AndreaLanfranchi** [comment]
> 2432 MB

Raise it 4Gb at least. And retry.

**Comment by nkoinhub** [comment]
Raised it to 8000Mb, but still no change. (Machine restart done)

**Comment by nkoinhub** [comment]
The dump:

ethminer -U http://eth-eu.dwarfpool.com:80/36e1aedb898a820f654b97c1c95b772c869276bf
 m 20:12:07 main     ethminer 0.15.0rc1
 m 20:12:07 main     Build: windows/release
cu 20:12:07 main     Using grid size: 8192, block size: 128
 i 20:12:07 main     Selected pool eth-eu.dwarfpool.com:80
 i 20:12:08 getwork  Connected to eth-eu.dwarfpool.com
 i 20:12:08 getwork  Spinning up miners...
 i 20:12:08 cuda-0   No work. Pause for 3 s.
 i 20:12:08 getwork  Job: #0ecba1b2... eth-eu.dwarfpool.com
 i 20:12:08 getwork  Pool difficulty: 2.00K megahash
 i 20:12:08 getwork  New epoch 201
 i 20:12:11 cuda-0   Initialising miner 0
cu 20:12:11 cuda-0   Using device: GeForce GT 730 (Compute 3.5)
 m 20:12:12 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
cu 20:12:17 cuda-0   Set Device to current
cu 20:12:17 cuda-0   Resetting device
cu 20:12:17 cuda-0   Allocating light with size: 43122368
 i 20:12:17 getwork  Job: #e28cd330... eth-eu.dwarfpool.com
cu 20:12:17 cuda-0   Generating mining buffers
cu 20:12:17 cuda-0   Generating DAG for GPU #0 with dagSize: 2759851648 gridSize: 8192
 m 20:12:17 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 20:12:22 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 X 20:12:25 cuda-0   Fatal GPU error: CUDA error in func set_header at line 144 unspecified launch failure
 X 20:12:25 cuda-0   Terminating.

**Comment by AndreaLanfranchi** [comment]
Try reducing --cuda-block-size

```
ethminer -U -P http://eth-eu.dwarfpool.com:80/36e1aedb898a820f654b97c1c95b772c869276bf --cuda-block-size 96
```

If it does not work try running in OpenCL mode

```
ethminer -G -P http://eth-eu.dwarfpool.com:80/36e1aedb898a820f654b97c1c95b772c869276bf 
```

**Comment by quetzalcoatl** [comment]
Sorry for late response, here's the data:

- Win 10 Home
- ethminer 0.15.0rc2 build windows/release/msvc
- two cards: internal Intel HD Graphics 5500 + NVIDIA GeForce 920M

list CUDA devices
```
C:\Temp\btc\ethminer-0.15.0rc2-Windows\bin>ethminer.exe -U --list-devices

Listing CUDA devices.
FORMAT: [deviceID] deviceName
[0] GeForce 920M
        Compute version: 3.5
        cudaDeviceProp::totalGlobalMem: 4294967296
        Pci: 0000:08:00
```

run on defaults:
```
C:\Temp\btc\ethminer-0.15.0rc2-Windows\bin>ethminer.exe stratum+ssl://xxxx@eu1.ethermine.org:5555 -U
 m 17:18:26 main     ethminer 0.15.0rc2
 m 17:18:26 main     Build: windows/release
cu 17:18:26 main     Using grid size: 8192, block size: 128
 i 17:18:26 main     Selected pool eu1.ethermine.org:5555
 i 17:18:26 stratum  Trying 164.132.200.54:5555 ...
 i 17:18:26 stratum  Connected to eu1.ethermine.org [164.132.200.54:5555]
 i 17:18:26 stratum  Spinning up miners...
 i 17:18:26 cuda-0   No work. Pause for 3 s.
 i 17:18:26 stratum  Subscribed to stratum server
 i 17:18:27 stratum  Authorized worker 0x4C2576878Fd4B5Fce01cDF6f27407ac68cB8d2CF
 i 17:18:27 stratum  Job: #428fefa6... eu1.ethermine.org [164.132.200.54:5555]
 i 17:18:27 stratum  Pool difficulty: 4.00K megahash
 i 17:18:27 stratum  New epoch 201
 i 17:18:27 stratum  Job: #33447ee7... eu1.ethermine.org [164.132.200.54:5555]
 i 17:18:29 cuda-0   Initialising miner 0
cu 17:18:30 cuda-0   Using device: GeForce 920M (Compute 3.5)
 m 17:18:31 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
cu 17:18:31 cuda-0   Set Device to current
cu 17:18:31 cuda-0   Resetting device
cu 17:18:32 cuda-0   Allocating light with size: 43122368
cu 17:18:32 cuda-0   Generating mining buffers
cu 17:18:32 cuda-0   Generating DAG for GPU #0 with dagSize: 2759851648 gridSize: 8192
 m 17:18:36 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 i 17:18:38 stratum  Job: #c2042357... eu1.ethermine.org [164.132.200.54:5555]
 m 17:18:41 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 i 17:18:44 stratum  Job: #dbe21d09... eu1.ethermine.org [164.132.200.54:5555]
 m 17:18:46 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 i 17:18:48 stratum  Job: #027181a9... eu1.ethermine.org [164.132.200.54:5555]
 m 17:18:51 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 17:18:56 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 17:19:01 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 17:19:06 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 17:19:11 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 i 17:19:12 stratum  Job: #45337130... eu1.ethermine.org [164.132.200.54:5555]
 m 17:19:17 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 i 17:19:21 stratum  Job: #835719d3... eu1.ethermine.org [164.132.200.54:5555]
 m 17:19:22 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 17:19:27 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 i 17:19:29 stratum  Job: #fb28145d... eu1.ethermine.org [164.132.200.54:5555]
 m 17:19:32 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 m 17:19:37 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 m 17:19:42 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 m 17:19:47 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 i 17:19:47 stratum  Job: #573b46be... eu1.ethermine.org [164.132.200.54:5555]
 m 17:19:52 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 i 17:19:53 stratum  Job: #d1e944b5... eu1.ethermine.org [164.132.200.54:5555]
cu 17:19:57 cuda-0   Generated DAG for GPU #0 in: 84938 ms.
 m 17:19:57 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 X 17:19:59 cuda-0   Fatal GPU error: CUDA error in func dev::eth::CUDAMiner::search at line 477 unspecified launch failure
 X 17:19:59 cuda-0   Terminating.
```

CUDA block size=96:
```
C:\Temp\btc\ethminer-0.15.0rc2-Windows\bin>ethminer.exe stratum+ssl://xxxx@eu1.ethermine.org:5555 -U --cuda-block-size 96
 m 17:21:13 main     ethminer 0.15.0rc2
 m 17:21:13 main     Build: windows/release
cu 17:21:13 main     Using grid size: 8192, block size: 96
 i 17:21:13 main     Selected pool eu1.ethermine.org:5555
 i 17:21:13 stratum  Trying 35.234.84.74:5555 ...
 i 17:21:13 stratum  Connected to eu1.ethermine.org [35.234.84.74:5555]
 i 17:21:13 stratum  Spinning up miners...
 i 17:21:13 cuda-0   No work. Pause for 3 s.
 i 17:21:13 stratum  Subscribed to stratum server
 i 17:21:13 stratum  Authorized worker 0x4C2576878Fd4B5Fce01cDF6f27407ac68cB8d2CF
 i 17:21:13 stratum  Job: #f816fd17... eu1.ethermine.org [35.234.84.74:5555]
 i 17:21:13 stratum  Pool difficulty: 4.00K megahash
 i 17:21:13 stratum  New epoch 201
 i 17:21:16 cuda-0   Initialising miner 0
cu 17:21:16 cuda-0   Using device: GeForce 920M (Compute 3.5)
 m 17:21:18 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
cu 17:21:18 cuda-0   Set Device to current
cu 17:21:18 cuda-0   Resetting device
cu 17:21:18 cuda-0   Allocating light with size: 43122368
cu 17:21:19 cuda-0   Generating mining buffers
cu 17:21:19 cuda-0   Generating DAG for GPU #0 with dagSize: 2759851648 gridSize: 8192
 m 17:21:23 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 17:21:28 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 17:21:33 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 i 17:21:37 stratum  Job: #d3f797a8... eu1.ethermine.org [35.234.84.74:5555]
 m 17:21:38 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 17:21:43 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 i 17:21:46 stratum  Job: #a1e6e217... eu1.ethermine.org [35.234.84.74:5555]
 i 17:21:47 stratum  Job: #62270980... eu1.ethermine.org [35.234.84.74:5555]
 m 17:21:48 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 17:21:53 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 17:21:58 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 17:22:03 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 17:22:08 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 i 17:22:09 stratum  Job: #a2be0f72... eu1.ethermine.org [35.234.84.74:5555]
 m 17:22:13 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 i 17:22:13 stratum  Job: #d3249721... eu1.ethermine.org [35.234.84.74:5555]
 m 17:22:18 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 m 17:22:23 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 m 17:22:28 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 i 17:22:31 stratum  Job: #7fe020cb... eu1.ethermine.org [35.234.84.74:5555]
 m 17:22:34 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 m 17:22:39 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 i 17:22:39 stratum  Job: #8332ddc9... eu1.ethermine.org [35.234.84.74:5555]
cu 17:22:40 cuda-0   Generated DAG for GPU #0 in: 80844 ms.
 X 17:22:42 cuda-0   Fatal GPU error: CUDA error in func dev::eth::CUDAMiner::search at line 477 unspecified launch failure
 X 17:22:43 cuda-0   Terminating.
```

opencl on intel-hd-5500
```
Listing OpenCL devices.
FORMAT: [platformID] [deviceID] deviceName
[0] [0] Intel(R) HD Graphics 5500
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 6825898804
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1706474701
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 256
[1] [0] GeForce 920M
        CL_DEVICE_TYPE: GPU
        CL_DEVICE_GLOBAL_MEM_SIZE: 4294967296
        CL_DEVICE_MAX_MEM_ALLOC_SIZE: 1073741824
        CL_DEVICE_MAX_WORK_GROUP_SIZE: 1024

 m 17:27:11 main     ethminer 0.15.0rc2
 m 17:27:11 main     Build: windows/release
 i 17:27:11 main     Found suitable OpenCL device [Intel(R) HD Graphics 5500] with 6825898804 bytes of GPU memory
 i 17:27:11 main     Selected pool eu1.ethermine.org:5555
 i 17:27:11 stratum  Trying 35.234.119.196:5555 ...
 i 17:27:11 stratum  Connected to eu1.ethermine.org [35.234.119.196:5555]
 i 17:27:11 stratum  Spinning up miners...
cl 17:27:11 cl-0     No work. Pause for 3 s.
 i 17:27:12 stratum  Subscribed to stratum server
 i 17:27:12 stratum  Authorized worker 0x4C2576878Fd4B5Fce01cDF6f27407ac68cB8d2CF
 i 17:27:12 stratum  Job: #b553b022... eu1.ethermine.org [35.234.119.196:5555]
 i 17:27:12 stratum  Pool difficulty: 4.00K megahash
 i 17:27:12 stratum  New epoch 201
 i 17:27:12 stratum  Job: #53eaf21b... eu1.ethermine.org [35.234.119.196:5555]
cl 17:27:15 cl-0     Platform: Intel(R) OpenCL
cl 17:27:15 cl-0     Device:   Intel(R) HD Graphics 5500 / OpenCL 2.0
 m 17:27:16 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 i 17:27:17 stratum  Job: #b20ac5d0... eu1.ethermine.org [35.234.119.196:5555]
cl 17:27:17 cl-0     OpenCL kernel: Stable kernel
 i 17:27:17 stratum  Job: #bf953024... eu1.ethermine.org [35.234.119.196:5555]
cl 17:27:19 cl-0     Build info: fcl build 1 succeeded.
fcl build 2 succeeded.
bcl build succeeded.

cl 17:27:19 cl-0     Creating light cache buffer, size: 43122368
cl 17:27:19 cl-0     Creating DAG buffer, size: 2759851648
 X 17:27:19 cl-0     Creating DAG buffer failed: clCreateBuffer: CL_INVALID_BUFFER_SIZE (-61)
 X 17:27:19 cl-0     OpenCL Error: clEnqueueWriteBuffer: CL_INVALID_MEM_OBJECT (-38)
[and is stuck doing nothing, observes stratum, but does not attempt to generate DAG tree, etc]
```

opencl on gf920m
```
 m 17:32:26 main     ethminer 0.15.0rc2
 m 17:32:26 main     Build: windows/release
 i 17:32:27 main     Found suitable OpenCL device [GeForce 920M] with 4294967296 bytes of GPU memory
 i 17:32:27 main     Selected pool eu1.ethermine.org:5555
 i 17:32:27 stratum  Trying 35.234.81.9:5555 ...
 i 17:32:27 stratum  Connected to eu1.ethermine.org [35.234.81.9:5555]
 i 17:32:27 stratum  Spinning up miners...
cl 17:32:27 cl-0     No work. Pause for 3 s.
 i 17:32:27 stratum  Subscribed to stratum server
 i 17:32:27 stratum  Authorized worker 0x4C2576878Fd4B5Fce01cDF6f27407ac68cB8d2CF
 i 17:32:27 stratum  Job: #7fa0e57d... eu1.ethermine.org [35.234.81.9:5555]
 i 17:32:27 stratum  Pool difficulty: 4.00K megahash
 i 17:32:27 stratum  New epoch 201
cl 17:32:30 cl-0     Platform: NVIDIA CUDA
cl 17:32:30 cl-0     Device:   GeForce 920M / OpenCL 1.2 CUDA
 m 17:32:32 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
cl 17:32:33 cl-0     OpenCL kernel: Stable kernel
cl 17:32:34 cl-0     Build info:

cl 17:32:34 cl-0     Creating light cache buffer, size: 43122368
cl 17:32:34 cl-0     Creating DAG buffer, size: 2759851648
cl 17:32:34 cl-0     Loading kernels
cl 17:32:34 cl-0     Writing light cache buffer
cl 17:32:34 cl-0     Creating buffer for header.
cl 17:32:34 cl-0     Creating mining buffer
 i 17:32:36 stratum  Job: #97b91065... eu1.ethermine.org [35.234.81.9:5555]
 i 17:32:36 stratum  Job: #4b5270da... eu1.ethermine.org [35.234.81.9:5555]
 m 17:32:37 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 X 17:32:37 cl-0     OpenCL init failed: clFinish: CL_INVALID_COMMAND_QUEUE (-36)
 X 17:32:37 cl-0     OpenCL Error: clEnqueueWriteBuffer: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)
[and is stuck doing nothing, observes stratum, but does not attempt to generate DAG tree, etc]
```

mixed cuda/opencl
```
C:\Temp\btc\ethminer-0.15.0rc2-Windows\bin>ethminer.exe stratum+ssl://xxxx@eu1.ethermine.org:5555 -X --opencl-platform 1
 m 17:35:36 main     ethminer 0.15.0rc2
 m 17:35:36 main     Build: windows/release
 i 17:35:36 main     Found suitable OpenCL device [GeForce 920M] with 4294967296 bytes of GPU memory
cu 17:35:36 main     Using grid size: 8192, block size: 128
 i 17:35:36 main     Selected pool eu1.ethermine.org:5555
 i 17:35:36 stratum  Trying 35.234.112.115:5555 ...
 i 17:35:36 stratum  Connected to eu1.ethermine.org [35.234.112.115:5555]
 i 17:35:36 stratum  Spinning up miners...
 i 17:35:36 cuda-0   No work. Pause for 3 s.
cl 17:35:36 cl-1     No work. Pause for 3 s.
 i 17:35:36 stratum  Subscribed to stratum server
 i 17:35:37 stratum  Authorized worker 0x4C2576878Fd4B5Fce01cDF6f27407ac68cB8d2CF
 i 17:35:37 stratum  Job: #369d6f06... eu1.ethermine.org [35.234.112.115:5555]
 i 17:35:37 stratum  Pool difficulty: 4.00K megahash
 i 17:35:37 stratum  New epoch 201
 i 17:35:39 cuda-0   Initialising miner 0
cl 17:35:39 cl-1     Platform: NVIDIA CUDA
cl 17:35:39 cl-1     Device:   GeForce 920M / OpenCL 1.2 CUDA
cu 17:35:39 cuda-0   Using device: GeForce 920M (Compute 3.5)
 m 17:35:41 main     Speed   0.00 Mh/s    gpu/0  0.00  gpu/1  0.00  [A0+0:R0+0:F0] Time: 00:00
cl 17:35:41 cl-1     OpenCL kernel: Stable kernel
cu 17:35:41 cuda-0   Set Device to current
cu 17:35:41 cuda-0   Resetting device
cl 17:35:41 cl-1     Build info:

cl 17:35:41 cl-1     Creating light cache buffer, size: 43122368
cl 17:35:41 cl-1     Creating DAG buffer, size: 2759851648
cl 17:35:41 cl-1     Loading kernels
cl 17:35:41 cl-1     Writing light cache buffer
cl 17:35:41 cl-1     Creating buffer for header.
cl 17:35:41 cl-1     Creating mining buffer
 X 17:35:45 cl-1     OpenCL init failed: clFinish: CL_INVALID_COMMAND_QUEUE (-36)
 X 17:35:45 cl-1     OpenCL Error: clEnqueueWriteBuffer: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)
cu 17:35:45 cuda-0   Allocating light with size: 43122368
[and exists without 'terminating' message]
```

Strangely, the line-number has changed since my original report. I have not changed the miner version. However, there's a chance that automatic windows-update has updated graphic card drivers. Unlikely, but maybe. I have no idea.

**Comment by nkoinhub** [comment]
It's now running in OpenCL mode i.e. command used is:
ethminer -G -P http://eth-eu.dwarfpool.com:80/36e1aedb898a820f654b97c1c95b772c869276bf 

Kindly see my update. Here is the dump:

ethminer -G -P http://eth-eu.dwarfpool.com:80/36e1aedb898a820f654b97c1c95b772c869276bf
 m 15:34:23 main     ethminer 0.15.0rc1
 m 15:34:23 main     Build: windows/release
 i 15:34:23 main     Found suitable OpenCL device [Intel(R) HD Graphics 4600] with 1708759450 bytes of GPU memory
 i 15:34:23 main     Selected pool eth-eu.dwarfpool.com:80
 i 15:34:24 getwork  Connected to eth-eu.dwarfpool.com
 i 15:34:24 getwork  Spinning up miners...
cl 15:34:24 cl-0     No work. Pause for 3 s.
 i 15:34:24 getwork  Job: #a53e1a7b... eth-eu.dwarfpool.com
 i 15:34:24 getwork  Pool difficulty: 2.00K megahash
 i 15:34:24 getwork  New epoch 202
cl 15:34:27 cl-0     Platform: Intel(R) OpenCL
cl 15:34:27 cl-0     Device:   Intel(R) HD Graphics 4600 / OpenCL 1.2
 m 15:34:28 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
cl 15:34:31 cl-0     OpenCL kernel: Stable kernel
cl 15:34:31 cl-0     Build info: fcl build 1 succeeded.
fcl build 2 succeeded.
bcl build succeeded.

 i 15:34:31 cl-0     OpenCL device Intel(R) HD Graphics 4600 has insufficient GPU memory.1708759450 bytes of memory found < 2768232832 bytes of memory required
 X 15:34:31 cl-0     OpenCL Error: clEnqueueWriteBuffer: CL_INVALID_MEM_OBJECT (-38)
 m 15:34:33 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 15:34:38 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 15:34:43 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 i 15:34:43 getwork  Job: #c89feec0... eth-eu.dwarfpool.com
 m 15:34:48 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 15:34:53 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 15:34:58 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 15:35:03 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 i 15:35:22 getwork  Job: #7789e859... eth-eu.dwarfpool.com
 m 15:35:48 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 i 15:35:49 getwork  Job: #2226d552... eth-eu.dwarfpool.com
 m 15:35:53 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 m 15:35:58 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 m 15:36:03 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 m 15:36:08 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
 i 15:36:08 getwork  Job: #dc79c6a0... eth-eu.dwarfpool.com
 m 15:36:13 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:01
:  
:  
it is continued and time is getting incremental ahead 00:02 … 03 … 04 and on …

However, the above dump is showing some messages -

cl 15:34:27 cl-0     Platform: Intel(R) OpenCL
cl 15:34:27 cl-0     Device:   Intel(R) HD Graphics 4600 / OpenCL 1.2
 m 15:34:28 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
cl 15:34:31 cl-0     OpenCL kernel: Stable kernel
cl 15:34:31 cl-0     Build info: fcl build 1 succeeded.
fcl build 2 succeeded.
bcl build succeeded.

 i 15:34:31 cl-0     OpenCL device Intel(R) HD Graphics 4600 has insufficient GPU memory.1708759450 bytes of memory found < 2768232832 bytes of memory required

So, I'm NOT sure if it is working correctly now. Kindly help.

**Comment by AndreaLanfranchi** [comment]
No. It's not working at all.
OpenCL Mode is picking your internal graphic card which has not enough memory to hold the DAG file.

To detect your NVIDIA card use

```
ethminer -G -P http://eth-eu.dwarfpool.com:80/36e1aedb898a820f654b97c1c95b772c869276bf --opencl-platform 1
```

Not less important ... getwork mode is HIGHLY inefficient.
Use stratum mode

```
ethminer -G -P stratum+tcp://eth-eu.dwarfpool.com:8008/36e1aedb898a820f654b97c1c95b772c869276bf --opencl-platform 1
```

**Comment by nkoinhub** [comment]
Trials:

1. ethminer -G -P http://eth-eu.dwarfpool.com:80/36e1aedb898a820f654b97c1c95b772c869276bf --opencl-platform 1

C:\Program Files\Geth\miner>ethminer -G -P http://eth-eu.dwarfpool.com:80/36e1aedb898a820f654b97c1c95b772c869276bf --opencl-platform 1
 m 19:14:03 main     ethminer 0.15.0rc1
 m 19:14:03 main     Build: windows/release
 i 19:14:03 main     Found suitable OpenCL device [GeForce GT 730] with 4294967296 bytes of GPU memory
 i 19:14:04 main     Selected pool eth-eu.dwarfpool.com:80
 i 19:14:04 getwork  Connected to eth-eu.dwarfpool.com
 i 19:14:04 getwork  Spinning up miners...
cl 19:14:04 cl-0     No work. Pause for 3 s.
 i 19:14:04 getwork  Job: #170f0fe9... eth-eu.dwarfpool.com
 i 19:14:04 getwork  Pool difficulty: 2.00K megahash
 i 19:14:04 getwork  New epoch 202
 i 19:14:05 getwork  Job: #ef1e3980... eth-eu.dwarfpool.com
cl 19:14:07 cl-0     Platform: NVIDIA CUDA
cl 19:14:07 cl-0     Device:   GeForce GT 730 / OpenCL 1.2 CUDA
 m 19:14:09 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
cl 19:14:11 cl-0     OpenCL kernel: Stable kernel
cl 19:14:11 cl-0     Build info:

cl 19:14:11 cl-0     Creating light cache buffer, size: 43253696
cl 19:14:11 cl-0     Creating DAG buffer, size: 2768232832
cl 19:14:11 cl-0     Loading kernels
cl 19:14:11 cl-0     Writing light cache buffer
cl 19:14:11 cl-0     Creating buffer for header.
cl 19:14:11 cl-0     Creating mining buffer
 m 19:14:14 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 X 19:14:14 cl-0     OpenCL init failed: clFinish: CL_INVALID_COMMAND_QUEUE (-36)
 X 19:14:14 cl-0     OpenCL Error: clEnqueueWriteBuffer: CL_MEM_OBJECT_ALLOCATION_FAILURE (-4)
 m 19:14:19 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00

2. ethminer -G -P stratum+tcp://eth-eu.dwarfpool.com:8008/36e1aedb898a820f654b97c1c95b772c869276bf --opencl-platform 1

C:\Program Files\Geth\miner>ethminer -G -P stratum+tcp://eth-eu.dwarfpool.com:8008/36e1aedb898a820f654b97c1c95b772c869276bf --opencl-platform 1
 m 19:15:15 main     ethminer 0.15.0rc1
 m 19:15:15 main     Build: windows/release
 i 19:15:15 main     Found suitable OpenCL device [GeForce GT 730] with 4294967296 bytes of GPU memory
 i 19:15:15 main     Selected pool eth-eu.dwarfpool.com:8008
 i 19:15:15 stratum  Trying 188.165.34.183:8008 ...
 i 19:15:15 stratum  Connected to eth-eu.dwarfpool.com [188.165.34.183:8008]
 i 19:15:15 stratum  Spinning up miners...
cl 19:15:15 cl-0     No work. Pause for 3 s.
 i 19:15:15 stratum  Subscribed to stratum server
 i 19:15:16 stratum  Authorized worker
cl 19:15:18 cl-0     No work. Pause for 3 s.
 m 19:15:20 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 X 19:15:21 stratum  Got unknown method [] from pool. Discarding ...
 X 19:15:21 stratum  Got unknown method [] from pool. Discarding ...
 X 19:15:21 stratum  Got unknown method [] from pool. Discarding ...
cl 19:15:21 cl-0     No work. Pause for 3 s.
 X 19:15:21 stratum  Got unknown method [] from pool. Discarding …

3.  ethminer -U -G -P http://eth-eu.dwarfpool.com:80/36e1aedb898a820f654b97c1c95b772c869276bf

C:\Program Files\Geth\miner>ethminer -U -G -P http://eth-eu.dwarfpool.com:80/36e1aedb898a820f654b97c1c95b772c869276bf
 m 19:17:48 main     ethminer 0.15.0rc1
 m 19:17:48 main     Build: windows/release
 i 19:17:48 main     Found suitable OpenCL device [Intel(R) HD Graphics 4600] with 1708759450 bytes of GPU memory
 i 19:17:49 main     Selected pool eth-eu.dwarfpool.com:80
 i 19:17:50 main     Selected pool eth-eu.dwarfpool.com:80
 i 19:17:50 getwork  Connected to eth-eu.dwarfpool.com
 i 19:17:50 getwork  Spinning up miners...
cl 19:17:50 cl-0     No work. Pause for 3 s.
 i 19:17:50 getwork  Job: #683aadb5... eth-eu.dwarfpool.com
 i 19:17:50 getwork  Pool difficulty: 2.00K megahash
 i 19:17:50 getwork  New epoch 202
cl 19:17:53 cl-0     Platform: Intel(R) OpenCL
cl 19:17:53 cl-0     Device:   Intel(R) HD Graphics 4600 / OpenCL 1.2
 m 19:17:54 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
cl 19:17:56 cl-0     OpenCL kernel: Stable kernel
cl 19:17:56 cl-0     Build info: fcl build 1 succeeded.
fcl build 2 succeeded.
bcl build succeeded.

 i 19:17:56 cl-0     OpenCL device Intel(R) HD Graphics 4600 has insufficient GPU memory.1708759450 bytes of memory found < 2768232832 bytes of memory required
 X 19:17:56 cl-0     OpenCL Error: clEnqueueWriteBuffer: CL_INVALID_MEM_OBJECT (-38)


4. ethminer -U -P http://eth-eu.dwarfpool.com:80/36e1aedb898a820f654b97c1c95b772c869276bf

C:\Program Files\Geth\miner>ethminer -U -P http://eth-eu.dwarfpool.com:80/36e1aedb898a820f654b97c1c95b772c869276bf
 m 19:21:16 main     ethminer 0.15.0rc1
 m 19:21:16 main     Build: windows/release
cu 19:21:16 main     Using grid size: 8192, block size: 128
 i 19:21:17 main     Selected pool eth-eu.dwarfpool.com:80
 i 19:21:17 getwork  Connected to eth-eu.dwarfpool.com
 i 19:21:17 getwork  Spinning up miners...
 i 19:21:17 cuda-0   No work. Pause for 3 s.
 i 19:21:17 getwork  Job: #97fa203c... eth-eu.dwarfpool.com
 i 19:21:17 getwork  Pool difficulty: 2.00K megahash
 i 19:21:17 getwork  New epoch 202
 i 19:21:20 cuda-0   Initialising miner 0
cu 19:21:20 cuda-0   Using device: GeForce GT 730 (Compute 3.5)
 m 19:21:22 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
cu 19:21:25 cuda-0   Set Device to current
cu 19:21:25 cuda-0   Resetting device
cu 19:21:25 cuda-0   Allocating light with size: 43253696
cu 19:21:26 cuda-0   Generating mining buffers
cu 19:21:26 cuda-0   Generating DAG for GPU #0 with dagSize: 2768232832 gridSize: 8192
 m 19:21:27 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 m 19:21:32 main     Speed   0.00 Mh/s    gpu/0  0.00  [A0+0:R0+0:F0] Time: 00:00
 i 19:21:33 getwork  Job: #a9feb26d... eth-eu.dwarfpool.com
 X 19:21:43 cuda-0   Fatal GPU error: CUDA error in func set_header at line 144 unspecified launch failure
 X 19:21:46 cuda-0   Terminating.


NO success. Can it be traced from these 4 trials please?

**Comment by nkoinhub** [comment]
Is there any solution on this? Kindly let me know, if more information is required.

**Comment by nkoinhub** [comment]
Would it help to have an additional GPU?

**Comment by AndreaLanfranchi** [comment]
I'm afraid GT 730 is too weak to mine.
Either you install a more powerful card (at the very least a Gtx 1050) with a more recent compute level (6 or more) or I'm afraid you have to give up.
