### ISSUE TITLE
0.14.0.dev4 windows - no no response received in 2 seconds.

### ISSUE THREAD

**Issue by paddymahoney** [ethereum-mining/ethminer#936]
Getting a fatal error on 0.14.0.dev4 on windows: 

```
 m  00:51:37|main    |  Speed  85.62 Mh/s    gpu/0 53.58  gpu/1 32.04  [A2098+33:R0+0:F0] Time: 27:45
  m  00:51:42|main    |  Speed  86.00 Mh/s    gpu/0 53.84  gpu/1 32.16  [A2098+33:R0+0:F0] Time: 27:45
  m  00:51:47|main    |  Speed  86.15 Mh/s    gpu/0 53.88  gpu/1 32.27  [A2098+33:R0+0:F0] Time: 27:45
  m  00:51:52|main    |  Speed  86.28 Mh/s    gpu/0 53.93  gpu/1 32.36  [A2098+33:R0+0:F0] Time: 27:45
  m  00:51:57|main    |  Speed  86.28 Mh/s    gpu/0 53.93  gpu/1 32.36  [A2098+33:R0+0:F0] Time: 27:45
  m  00:52:02|main    |  Speed  86.12 Mh/s    gpu/0 53.77  gpu/1 32.35  [A2098+33:R0+0:F0] Time: 27:45
  m  00:52:07|main    |  Speed  86.27 Mh/s    gpu/0 53.92  gpu/1 32.35  [A2098+33:R0+0:F0] Time: 27:45
  i  00:52:08|cuda-1  |  Nonce 0x618963502b3cfa7d submitted to eu1.ethermine.org
  X  00:52:11|stratum |  No no response received in 2 seconds.
  m  00:52:12|main    |  Speed  86.43 Mh/s    gpu/0 54.08  gpu/1 32.36  [A2098+33:R0+0:F0] Time: 27:45
  i  00:52:14|cuda-0  |  Nonce 0x6189625068aafb54 submitted to eu1.ethermine.org
  m  00:52:17|main    |  Speed  86.17 Mh/s    gpu/0 53.86  gpu/1 32.31  [A2098+33:R0+0:F0] Time: 27:45
  m  00:52:22|main    |  Speed  86.32 Mh/s    gpu/0 54.01  gpu/1 32.31  [A2098+33:R0+0:F0] Time: 27:45
  m  00:52:27|main    |  Speed  86.47 Mh/s    gpu/0 54.16  gpu/1 32.31  [A2098+33:R0+0:F0] Time: 27:46
  i  00:52:28|cuda-1  |  Nonce 0x618963504febe088 submitted to eu1.ethermine.org
  i  00:52:31|stratum |  Disconnected from eu1.ethermine.org
  i  00:52:31|stratum |  Shutting down miners...
  i  00:52:31|stratum |  Retrying in 3 ...
  i  00:52:32|stratum |  Retrying in 2 ...
  m  00:52:32|main    |  not-connected
  i  00:52:33|stratum |  Retrying in 1 ...
  X  00:52:34|stratum |  Handle response failed: protocol is shutdown
  X  00:52:34|stratum |  Handle response failed: protocol is shutdown
  m  13:00:01|main    |  not-connected
```

- with --stratum-ssl specified.

**Comment by digitalpara** [comment]
the same also here with this version ethminer 0.14.0rc4, until now it becomes a misery with mining ethminer 0.14.0rc4, miner stops and goes no further, please watchdog please just like Phoenixminer or Claymore there are enough examples but ethminer developers are sleeping .

i 14: 52: 31 | stratum | Disconnected from eu1.ethermine.org
i 14: 52: 31 | stratum | Shutting down miners ...
i 14: 52: 31 | stratum | Retrying in 3 ...
i 14: 52: 32 | stratum | Retrying in 2 ...
m 14: 52: 32 | main | not-connected
i 14: 52: 33 | stratum | Retrying in 1 ...
X 14: 52: 34 | stratum | Handle response failed: protocol is shutdown
X 14: 52: 34 | stratum | Handle response failed: protocol is shutdown
m 15: 00: 01 | main | not-connected

with --stratum-ssl specified.
i use this with ethminer 
Download: https://github.com/digitalpara/WiNETH
Download: https://mirrorace.com/m/1qikt

**Comment by shawnsmithdev** [comment]
Same.  Win10, GTX 1070. Won't post logs as it was default verbosity and look basically the same, so probably not helpful.

cli args:
```txt
ethminer --farm-retries 10 --farm-recheck 2000 -U -RH -HWMON 1 \
-P stratum+ssl://0x0000000000000000000000000000000000000000.worker@us2.ethermine.org:5555 \
-P stratum+ssl://0x0000000000000000000000000000000000000000.worker@us1.ethermine.org:5555
```

**Comment by AndreaLanfranchi** [comment]
Please redo your tests with ethminer 0.14.0rc6

**Comment by AndreaLanfranchi** [comment]
@digitalpara 

< but ethminer developers are sleeping .

Please keep always in mind that we're giving our spare time for free. No one gets paid for this nor you pay a single dime for using ethminer.

**Comment by faithless1108** [comment]
@digitalpara THANK YOU FOR ALL THE WORK AND YOUR FREE TIME!!!!


@Topic: 0.14.0rc6 also not working for me. Same error on PIMP 2.5

**Comment by AndreaLanfranchi** [comment]
Solved in 
* 0.14.rc7
* 0.15.dev6

**Comment by paddymahoney** [comment]
Confirm 0.15.dev6 resolves my issue

**Comment by faithless1108** [comment]
Its not fixed for me on Linux with 0.15.dev6

![image](https://user-images.githubusercontent.com/6443821/39516720-0fcece5e-4dfe-11e8-856a-d3eb329d853b.png)

**Comment by AndreaLanfranchi** [comment]
Please try latest. We've pushed some little changes few minutes ago.
And report back.

**Comment by faithless1108** [comment]
kk, give it a try.

**Comment by faithless1108** [comment]
Same Error after about 10 Minutes

**Comment by faithless1108** [comment]
I use a Cable-Connection with 400mbit down/20 mbit up. Normally my submissions take ~20ms. It is dynamic IP but the IP changes every 6 - 8 Weeks. 

OK, thank you. I try to provide fast feedback if you have a new release.

**Comment by AndreaLanfranchi** [comment]
@faithless1108 
can you describe your environment ?
CPU and flavour (x86/x64) ?
OS and flavour

Thanks

**Comment by faithless1108** [comment]
Hey, 

sure... All it takes to solve this.

CPU: CPU Intel Celeron G3900 2x 2.80GHz (64Bit)
MoBo: ASRock BTC Pro H110
RAM: 4GB (Cheapest  I could find, dont know the Vendor)

OS: PIMP 2.5 (https://getpimp.org/, I think its a modified Ubuntu 16.04.4 LTS)

Connected via LAN-Cable to Router. Internetconnection is a verry stable Calbe-Broadband-Connection with 400Mbit down- / 20 Mbit upstream. 

You need something else?

Thanks for your greate support Mate!!

**Comment by faithless1108** [comment]
I found the Invoce. Its Crucial RAM

**Comment by AndreaLanfranchi** [comment]
Do you have other rigs ? If so .. it happens only on one of them or it's random ?

From the log I see, apparently, your machine takes 20 seconds to run a very simple disconnection of the socket (code follows) which, coupled with your exhuberant network configuration, leads me to think you might have a network card error.

This code takes 20 seconds to run on your machine

```
	if (m_socket && m_socket->is_open()) { 

		try {
		
			boost::system::error_code sec;

			if (m_conn.SecLevel() != SecureLevel::NONE) {
				m_securesocket->shutdown(sec);
			}
			else {
				m_nonsecuresocket->shutdown(boost::asio::ip::tcp::socket::shutdown_both, sec);
			}

			m_socket->close();
			m_io_service.stop();
		}
		catch (std::exception const& _e) {
			cwarn << "Error while disconnecting:" << _e.what();
		}

		m_securesocket = nullptr;
		m_nonsecuresocket = nullptr;
		m_socket = nullptr;
	}

```

**Comment by faithless1108** [comment]
It's the only Rig I have. 

But with Claymore-Miner there is absolutely no problem. SSH and all the Stuff works and is stable (Miner-Test for Hours). I really dont think it's the Card...

**Comment by AndreaLanfranchi** [comment]
In other words ... 

shutdown : this should ensure that any pending operations on the socket are properly cancelled and any buffers are flushed prior to the call to socket.close.

but ... you're shutting down because you previously had a 2 seconds response timeout on the socket thus, somehow, your network card was already non responding.

I've seen similar problems with same MOBO as yours at high overclocking values (network card becomes unresponsive and takes time to "restore").

Would ask you to :
* ensure MOBO BIOS is up to date
* try a batch test with NO overclocking
* check with dmesg if there are relevant messages about network card.

**Comment by AndreaLanfranchi** [comment]
>But with Claymore-Miner there is absolutely no problem. SSH and all the Stuff works and is stable (Miner-Test for Hours). I really dont think it's the Card...

We do not know how Claymore implements socket management as it's code is closed.
Maybe they don't care about a clean shutdown (and drop the socket abruptly) or don't care about the 2 seconds timeout on response.

**Comment by AndreaLanfranchi** [comment]
Segfault error 4 means thread name "stratum" could not read and the only thing it reads is socket data over the network card (look ip - instruction pointer is always the same 0000000000545005 - we have only one instruction where we invoke read). This causes your 2 seconds reponse time-out

Segfault error 15 means stratum could not write to socket.

Think it's machine related ... not code related.

**Comment by faithless1108** [comment]
>Think it's machine related ... not code related.<

I'm with you. I try to do the things you gave me for homework and look how it goes... Otherwise I'm addicted to Claymore :(

**Comment by paddymahoney** [comment]
Update: Ah too bad, ran into the error again with 0.15.dev6:
X 10:33:38|stratum | No response received in 2 seconds.
i 10:33:39|stratum | Disconnected from us1.ethermine.org [18.219.59.155:5555]
i 10:33:42|stratum | Shutting down miners...
m 10:33:44|main | not-connected
i 10:33:46|stratum | Retrying in 3 ...
m 10:33:49|main | not-connected
i 10:33:49|stratum | Retrying in 2 ...
i 10:33:50|stratum | Retrying in 1 ...

Windows then reports that ethminer.exe stopped working. I would be happy if the miner continued to run rather than die, just so that I don't run it under a supervisor

**Comment by AndreaLanfranchi** [comment]
Solved in #1135
